- hosts: all
  tasks:
    - name: stop container
      shell: docker container stop docker-container
    - name: remove container
      shell: docker container rm docker-container
    - name: remove image
      shell: docker image rm fazzlerabby/ci
    - name: create conbtainer
      shell: docker container run -itd --name docker-container -p 9000:80 fazzlerabby/ci
